# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.9/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.9/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zero_two/Desktop/SuperVPN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zero_two/Desktop/SuperVPN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.9/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.9/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zero_two/Desktop/SuperVPN/CMakeFiles /Users/zero_two/Desktop/SuperVPN//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zero_two/Desktop/SuperVPN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named supervpn

# Build rule for target.
supervpn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 supervpn
.PHONY : supervpn

# fast build rule for target.
supervpn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/build
.PHONY : supervpn/fast

src/charm.o: src/charm.cpp.o
.PHONY : src/charm.o

# target to build an object file
src/charm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/charm.cpp.o
.PHONY : src/charm.cpp.o

src/charm.i: src/charm.cpp.i
.PHONY : src/charm.i

# target to preprocess a source file
src/charm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/charm.cpp.i
.PHONY : src/charm.cpp.i

src/charm.s: src/charm.cpp.s
.PHONY : src/charm.s

# target to generate assembly for a file
src/charm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/charm.cpp.s
.PHONY : src/charm.cpp.s

src/os.o: src/os.cpp.o
.PHONY : src/os.o

# target to build an object file
src/os.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/os.cpp.o
.PHONY : src/os.cpp.o

src/os.i: src/os.cpp.i
.PHONY : src/os.i

# target to preprocess a source file
src/os.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/os.cpp.i
.PHONY : src/os.cpp.i

src/os.s: src/os.cpp.s
.PHONY : src/os.s

# target to generate assembly for a file
src/os.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/os.cpp.s
.PHONY : src/os.cpp.s

src/vpn.o: src/vpn.cpp.o
.PHONY : src/vpn.o

# target to build an object file
src/vpn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/vpn.cpp.o
.PHONY : src/vpn.cpp.o

src/vpn.i: src/vpn.cpp.i
.PHONY : src/vpn.i

# target to preprocess a source file
src/vpn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/vpn.cpp.i
.PHONY : src/vpn.cpp.i

src/vpn.s: src/vpn.cpp.s
.PHONY : src/vpn.s

# target to generate assembly for a file
src/vpn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/supervpn.dir/build.make CMakeFiles/supervpn.dir/src/vpn.cpp.s
.PHONY : src/vpn.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... supervpn"
	@echo "... src/charm.o"
	@echo "... src/charm.i"
	@echo "... src/charm.s"
	@echo "... src/os.o"
	@echo "... src/os.i"
	@echo "... src/os.s"
	@echo "... src/vpn.o"
	@echo "... src/vpn.i"
	@echo "... src/vpn.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

